### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by targos** [nodejs/changelog-maker#54]
Just noting a few warnings I got while preparing the v9.9.0 release:

```console
$ NODE_OPTIONS="--trace-warnings" changelog-maker --group --start-ref v9.8.0
(node:10896) [DEP0005] DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
    at showFlaggedDeprecation (buffer.js:139:13)
    at new Buffer (buffer.js:160:3)
    at BufferList.copy (/home/mzasso/.nvm/versions/node/v9.8.0/lib/node_modules/changelog-maker/node_modules/gitexec/node_modules/bl/bl.js:108:19)
    at BufferList.slice (/home/mzasso/.nvm/versions/node/v9.8.0/lib/node_modules/changelog-maker/node_modules/gitexec/node_modules/bl/bl.js:99:15)
    at BufferList.end (/home/mzasso/.nvm/versions/node/v9.8.0/lib/node_modules/changelog-maker/node_modules/gitexec/node_modules/bl/bl.js:89:31)
    at Socket.onend (_stream_readable.js:602:10)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Your GitHub username: targos
Your GitHub password: XXXXXX

(node:10896) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
    at Object.exports.enroll (timers.js:407:13)
    at TLSSocket.Socket.setTimeout (net.js:369:12)
    at TLSSocket.<anonymous> (_http_client.js:725:14)
    at Object.onceWrapper (events.js:272:13)
    at TLSSocket.emit (events.js:185:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1157:10)
Your GitHub OTP/2FA Code (optional): XXXXXX
(node:10896) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
    at Object.exports.enroll (timers.js:407:13)
    at TLSSocket.Socket.setTimeout (net.js:369:12)
    at TLSSocket.<anonymous> (_http_client.js:725:14)
    at Object.onceWrapper (events.js:272:13)
    at TLSSocket.emit (events.js:185:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1157:10)
```

**Comment by XhmikosR** [comment]
@targos could you please try #61?

**Comment by XhmikosR** [comment]
I've confirmed this will be fixed when gitexec is updated with the newer bl version.
